import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import Footer from "@/components/Footer";
import Head from "@/components/Head";
import { AuthProvider } from "@/context/AuthContext";
import CookiesBanner from "@/components/CookiesBanner";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '600'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <AuthProvider>
          <Toaster />
          <Head/>
          {children}
          <Footer />
          <CookiesBanner />
        </AuthProvider>
      </body>
    </html>
  );
}
